### ISSUE TITLE
� character while compressing

### ISSUE THREAD

**Issue by nrotta** [MayhemYDG/iltorb#10]
I'm working on supporting brotli compression for hapijs. I'm getting a weird error when trying to use the lib. This is my code:

```
const compress = require('iltorb').compress;
const message = { 'msg': 'hello world.' };

compress(new Buffer(JSON.stringify(message)), (err, buf) => {
  console.log(buf.toString());
});
```
This results in:
```
> �{"msg":"hello world."}
```
Not sure what I'm doing wrong. Any help?

**Comment by MayhemYDG** [comment]
It looks like brotli doesn't bother compressing when the buffer is too small, and this `�` character your console prints is just a binary header. If you decompress that buffer you'll get the expected text.
I checked with the binary executable, and got the exact same result, so it's not a bug!

**Comment by nrotta** [comment]
Hey. Thanks for the really quick response. You are correct. I increased the size of the payload and it indeed compressed correctly. Thanks.
