### ISSUE TITLE
iltorb fails to build on Windows 8.1

### ISSUE THREAD

**Issue by adamgcraig** [MayhemYDG/iltorb#13]
Running the Yeoman generator angular-fullstack on a 64-bit Windows 8.1 machine produces the following error at the end of a much longer log of installations:
`173890 info lifecycle iltorb@1.0.12~install: iltorb@1.0.12
173891 verbose lifecycle iltorb@1.0.12~install: unsafe-perm in lifecycle true
173892 verbose lifecycle iltorb@1.0.12~install: PATH: C:\Users\a'\AppData\Roaming\nvm\v6.4.0\node_modules\npm\bin\node-gyp-bin;C:\Users\a'\Documents\UploadTest\ACraig\software\UploadTest\node_modules\iltorb\node_modules\.bin;C:\Users\a'\Documents\UploadTest\ACraig\software\UploadTest\node_modules\.bin;C:\Program Files\nodejs;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files (x86)\MiKTeX 2.9\miktex\bin\;C:\Program Files (x86)\MySQL\MySQL Fabric 1.5 & MySQL Utilities 1.5\;C:\Program Files (x86)\MySQL\MySQL Fabric 1.5 & MySQL Utilities 1.5\Doctrine extensions for PHP\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files\TortoiseGit\bin;C:\Program Files\Git\cmd;%NVM_HOME%;%NVM_SYMLINK%;C:\Users\a'\AppData\Roaming\npm,C:\"Program Files"\MongoDB\Server\3.2\bin;C:\Python27\python.exe;C:\Users\a'\AppData\Roaming\nvm;C:\Program Files\nodejs
173893 verbose lifecycle iltorb@1.0.12~install: CWD: C:\Users\a'\Documents\UploadTest\ACraig\software\UploadTest\node_modules\iltorb
173894 silly lifecycle iltorb@1.0.12~install: Args: [ '/d /s /c', 'node-gyp rebuild' ]
173895 silly lifecycle iltorb@1.0.12~install: Returned: code: 1  signal: null
173896 info lifecycle iltorb@1.0.12~install: Failed to exec install script
173897 verbose unlock done using C:\Users\a'\AppData\Roaming\npm-cache\_locks\staging-c4819cc1d46684e7.lock for C:\Users\a'\Documents\UploadTest\ACraig\software\UploadTest\node_modules\.staging
173898 silly rollbackFailedOptional Starting
173899 silly rollbackFailedOptional Finishing
173900 silly runTopLevelLifecycles Starting
173901 silly runTopLevelLifecycles Finishing
173902 silly install printInstalled
173903 warn optional Skipping failed optional dependency /chokidar/fsevents:
173904 warn notsup Not compatible with your operating system or architecture: fsevents@1.0.14
173905 warn optional Skipping failed optional dependency /stylint/chokidar/fsevents:
173906 warn notsup Not compatible with your operating system or architecture: fsevents@1.0.14
173907 warn optional Skipping failed optional dependency /gulp-watch/chokidar/fsevents:
173908 warn notsup Not compatible with your operating system or architecture: fsevents@1.0.14
173909 verbose stack Error: iltorb@1.0.12 install: `node-gyp rebuild`
173909 verbose stack Exit status 1
173909 verbose stack     at EventEmitter.<anonymous> (C:\Users\a'\AppData\Roaming\nvm\v6.4.0\node_modules\npm\lib\utils\lifecycle.js:242:16)
173909 verbose stack     at emitTwo (events.js:106:13)
173909 verbose stack     at EventEmitter.emit (events.js:191:7)
173909 verbose stack     at ChildProcess.<anonymous> (C:\Users\a'\AppData\Roaming\nvm\v6.4.0\node_modules\npm\lib\utils\spawn.js:40:14)
173909 verbose stack     at emitTwo (events.js:106:13)
173909 verbose stack     at ChildProcess.emit (events.js:191:7)
173909 verbose stack     at maybeClose (internal/child_process.js:852:16)
173909 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
173910 verbose pkgid iltorb@1.0.12
173911 verbose cwd C:\Users\a'\Documents\UploadTest\ACraig\software\UploadTest
173912 error Windows_NT 6.3.9600
173913 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
173914 error node v6.4.0
173915 error npm  v3.10.3
173916 error code ELIFECYCLE
173917 error iltorb@1.0.12 install: `node-gyp rebuild`
173917 error Exit status 1
173918 error Failed at the iltorb@1.0.12 install script 'node-gyp rebuild'.
173918 error Make sure you have the latest version of node.js and npm installed.
173918 error If you do, this is most likely a problem with the iltorb package,
173918 error not with npm itself.
173918 error Tell the author that this fails on your system:
173918 error     node-gyp rebuild
173918 error You can get information on how to open an issue for this project with:
173918 error     npm bugs iltorb
173918 error Or if that isn't available, you can get their info via:
173918 error     npm owner ls iltorb
173918 error There is likely additional logging output above.
173919 verbose exit [ 1, true ]
`
I have installed and am using Node.js 6.4.0 and npm 3.10.3, which are the latest versions available.

**Comment by addaleax** [comment]
Hi! I’m not the owner here, but maybe I can still help… have you tried building this outside of your user directory? Names like `C:\Users\a'\` can easily throw off build systems.

**Comment by MayhemYDG** [comment]
@adamgcraig did addaleax's suggestion help?
