### ISSUE TITLE
node-gyp rebuild

### ISSUE THREAD

**Issue by malorus** [MayhemYDG/iltorb#15]
I've got an error generating the angular-fullstack-project via `yo angular-fullstack`. 
```

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! iltorb@1.0.12 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the iltorb@1.0.12 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the iltorb package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
```
Any way to solve that?

**Comment by MayhemYDG** [comment]
Have you tried installing the [Windows Build Tools](https://github.com/felixrieseberg/windows-build-tools/blob/master/README.md)?

**Comment by malorus** [comment]
Yes, I've already done what's recommended here: https://github.com/nodejs/node-gyp#installation
But without luck.  Is the error important and should therefore be solved? Or can I develop apps with that error?

**Comment by MayhemYDG** [comment]
You shouldn't need to install node-gyp manually, it's bundled in npm.

I'd suggest updating npm with `npm i -g npm`, as it should update its internal node-gyp, then try installing iltorb again to see if it still give you errors. `npm i iltorb`.

**Comment by malorus** [comment]
Nope, still does not work. But when executing `npm i iltorb` I get the info that "CL.exe" could not be found. So it seems, here is the culprit. But I still don't know how to solve that as all built tools are already installed. Thus "CL.exe" should be in the right place...

**Comment by MayhemYDG** [comment]
Maybe try installing the build tools again? The node-gyp readme also recommends running it "from an elevated PowerShell or CMD.exe (run as Administrator)."

**Comment by MayhemYDG** [comment]
@malorus Is this still an issue? If CL.exe is still not found I'd suggest opening an issue with windows-build-tools.
