### ISSUE TITLE
[Feature Request] Consider using noge-pre-gyp?

### ISSUE THREAD

**Issue by Awk34** [MayhemYDG/iltorb#16]
Thanks for the great lib. I run the [Angular Full-Stack Generator](https://github.com/angular-fullstack/generator-angular-fullstack), a Yeoman generator for scaffolding full-stack web apps. In our latest major-version release, I switched from using Express's [`compression`](https://github.com/expressjs/compression) middleware to [`shrink-ray`](https://github.com/aickin/shrink-ray), which depends on this library for Brotli compression. 

We've had a huge number of users whom haven't been able to use the generator out-of-the-box, because they can't get `iltorb` to compile (I've noticed mainly on Windows). Would you consider using [node-pre-gyp](https://github.com/mapbox/node-pre-gyp) to pre-compile the native code for the most-used platforms?

**Comment by MayhemYDG** [comment]
I'll look into it.
Installing the [windows build tools](https://github.com/felixrieseberg/windows-build-tools) should be enough though, so you might want to recommend that in your README.

**Comment by Awk34** [comment]
I have :confused: ... I've still been getting so many GH issues about it I'm considering defaulting the generator back to `compression`

**Comment by MayhemYDG** [comment]
In your README you mention node-gyp, but not windows-build-tools directly.
You don't need to globally install node-gyp at all, as npm bundles it, so its installation guide is more secondary.

**Comment by Awk34** [comment]
Well, I linked to the [Installation section](https://github.com/nodejs/node-gyp#installation) for node-gyp.

I also have a section on it in the docs here: http://angular-fullstack.github.io/generator-angular-fullstack/Getting_Started/Prerequisites.html

**Comment by MayhemYDG** [comment]
Compiling Node Addons is easier than ever before on Windows, and it's generally not an issue for unix/macOS users.
`node-pre-gyp` seems more trouble than it's worth for me, sorry.

**Comment by designfrontier** [comment]
The one other advantage to this method would be reduced install time over compiling in place.
