### ISSUE TITLE
node-gyp fails to build on Windows 10

### ISSUE THREAD

**Issue by replete** [MayhemYDG/iltorb#17]
I am unable to install this module.
- Windows 10 Enterprise LTSB latest
- Windows Build Tools installed via npm
- Elevated Powershell
- Latest node-gyp, node, npm

Error log:

``` powershell
PS x:\xx\xx\xx-website> npm install --save-dev metalsmith-brotli

> iltorb@1.0.13 install x:\xx\xx\xx-website\node_modules\iltorb
> node-gyp rebuild


x:\xx\xx\xx-website\node_modules\iltorb>if not defined npm_config_node_gyp (node "C:\Users\xx\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Platforms\x64\PlatformToolsets\v140\Toolset.targets(3
6,5): error MSB8036: The Windows SDK version 8.1 was not found. Install the required version of Windows SDK
or change the SDK version in the project property pages or by right-clicking the solution and selecting "Ret
arget solution". [x:\xx\xx\xx-website\node_modules\iltorb\build\decode.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Platforms\x64\PlatformToolsets\v140\Toolset.targets(3
6,5): error MSB8036: The Windows SDK version 8.1 was not found. Install the required version of Windows SDK
or change the SDK version in the project property pages or by right-clicking the solution and selecting "Ret
arget solution". [x:\xx\xx\xx-website\node_modules\iltorb\build\encode.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\xx\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\xx\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd x:\xx\xx\xx-website\node_modules\iltorb
gyp ERR! node -v v6.7.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
xx-website@1.0.0 X:\xx\xx\xx-website
`-- (empty)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\phil\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save-dev" "metalsmith-brotli"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE

npm ERR! iltorb@1.0.13 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the iltorb@1.0.13 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the iltorb package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs iltorb
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls iltorb
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     X:\xx\xx\xx-website\npm-debug.log
npm ERR! code 1
PS X:\xx\xx\xx-website> npm install -g node-gyp
C:\Users\x\AppData\Roaming\npm\node-gyp -> C:\Users\x\AppData\Roaming\npm\node_modules\node-gyp\bin\node-gyp.js
- tweetnacl@0.14.3 node_modules\node-gyp\node_modules\bcrypt-pbkdf\node_modules\tweetnacl
C:\Users\x\AppData\Roaming\npm
`-- node-gyp@3.4.0
  +-- glob@7.1.1
  | `-- path-is-absolute@1.0.1
  +-- graceful-fs@4.1.9
  +-- npmlog@3.1.2
  | `-- gauge@2.6.0
  |   `-- string-width@1.0.2
  |     `-- code-point-at@1.0.1
  |       `-- number-is-nan@1.0.1
  +-- osenv@0.1.3
  | +-- os-homedir@1.0.2
  | `-- os-tmpdir@1.0.2
  `-- request@2.75.0
    +-- har-validator@2.0.6
    | `-- is-my-json-valid@2.15.0
    |   `-- jsonpointer@4.0.0
    `-- http-signature@1.1.1
      `-- sshpk@1.10.1
        `-- tweetnacl@0.14.3
```

**Comment by MayhemYDG** [comment]
>The Windows SDK version 8.1 was not found.

Please install the [windows-build-tools](https://github.com/felixrieseberg/windows-build-tools).

**Comment by replete** [comment]
I have installed `windows-build-tools` again and rebooted, resulting in the same error.

Perhaps this is an issue of 'windows-build-tools'? I have no experienced of this package, though I have Visual Studio 2015.3 installed anyway as my IDE.

**Comment by MayhemYDG** [comment]
Sounds like it.
I'd say open an issue with windows-build-tools, and try to install the "Windows SDK version 8.1" manually.

I could install iltorb just fine on the two windows machines I tried (win 7 and win 10), and they worked just fine with an updated npm and the windows-build-tools installed via elevated PowerShell. I'm not Windows export so that's as much help as I can give you.

**Comment by replete** [comment]
Thanks for your quick help. [It appears to be a current issue over at windows-buildtools](https://github.com/felixrieseberg/windows-build-tools/issues/9)

**Comment by replete** [comment]
I considered installing [Windows SDK 8.1](https://developer.microsoft.com/en-us/windows/downloads/windows-8-1-sdk) as a workaround, but it appears to be 1.5GB?

Are 1.5GB of libraries really necessary for the compilation of a simple console application?

Given the file size and the quick installation time of 'windows-build-tools', it would appear that the SDK is not installed at all by that package.

**Comment by MayhemYDG** [comment]
![image](https://cloud.githubusercontent.com/assets/567105/19241798/32e5fdc4-8f08-11e6-8eac-367c51ab9e85.png)
I don't get that 1.5GB figure from that installer.

I can't find a reference to the SDK itself in the windows-build-tools repo, maybe [this](https://github.com/felixrieseberg/windows-build-tools/blob/master/src/constants.js#L3) is enough?

**Comment by MayhemYDG** [comment]
Yeah [node-gyp doesn't mention](https://github.com/nodejs/node-gyp#installation) the SDK either.

**Comment by replete** [comment]
This is what I see:
![Windows SDK 8.1 install dialog in Windows 10](http://i.imgur.com/vHjZdCY.png)

I followed your suggestion and it appears that the SDK installation is blocked by the current installation of Visual Studio 2015. Follow [my comment over at windows-build-tools](https://github.com/felixrieseberg/windows-build-tools/issues/9#issuecomment-252662031)

**Comment by unsafecode** [comment]
I definitely don't think this is a reliable approach. Tried out today with `windows-build-tools` and still doesn't work. There **must** be an easier way.

**Comment by weestoater** [comment]
I too have had a right old time of it.  I install yoeman, then I ran generator - loads of issues.
Installed python; windows-build-tools then it still doesn't run.
There really **should be an easier way**

**Comment by cseufert** [comment]
Can binaries be downloaded (like node-sass does), and if the platform has no binary, then try building it?

**Comment by MayhemYDG** [comment]
Binaries are now available for 64bit linux/macos/windows starting with v1.1.0.

**Comment by joshcsmith13** [comment]
> Binaries are now available for 64bit linux/macos/windows starting with v1.1.0.

So... I'm sorry, but I'm still a node noob.  What does this mean? I'm still getting this error, and I've installed both the windows-build-tools and Windows SDK 8.1
