### ISSUE TITLE
Custom dictionary

### ISSUE THREAD

**Issue by felixsanz** [MayhemYDG/iltorb#20]
It is possible to pass a custom dictionary to brotli? If yes, how?

related: https://github.com/google/brotli/issues/168#issuecomment-142914648

**Comment by MayhemYDG** [comment]
Mmh, iltorb has no support for this.

**Comment by felixsanz** [comment]
Can this feature be added?

I wish I could provide a PR.

**Comment by MayhemYDG** [comment]
https://github.com/google/brotli/blob/7e347a7/enc/encode.c#L737
It looks doable. I guess you'd have to pass a dictionary as a buffer.

**Comment by felixsanz** [comment]
Yeah, something like an options property seems fine.

```javascript
{ dictionary: Buffer.from(dict) }
```

**Comment by MayhemYDG** [comment]
Available in v1.1.0.
