### ISSUE TITLE
node-gyp fails to build on Windows 7

### ISSUE THREAD

**Issue by mncourt** [MayhemYDG/iltorb#21]
Seems like random changes are being made to the 1.5.x angularjs tutorial and causing npm related errors and build errors.   Is anyone monitoring the activity of this by any chance?

Why is this called Mayhem???

mnoon@HORDPC160646 MINGW64 /c/Temp/angtut/angular.js (master)
$ bower install
bower closure-compiler#*    not-cached https://dl.google.com/closure-compiler/compiler-20140814.zip#*
bower closure-compiler#*       resolve https://dl.google.com/closure-compiler/compiler-20140814.zip#*
bower ng-closure-runner#*   not-cached https://raw.github.com/angular/ng-closure-runner/v0.2.4/assets/ng-closure-runner.zi
p#*
bower ng-closure-runner#*      resolve https://raw.github.com/angular/ng-closure-runner/v0.2.4/assets/ng-closure-runner.zi
p#*
bower jquery#3.1.0          not-cached https://github.com/jquery/jquery-dist.git#3.1.0
bower jquery#3.1.0             resolve https://github.com/jquery/jquery-dist.git#3.1.0
bower jquery-2.1#2.1.4      not-cached https://github.com/jquery/jquery-dist.git#2.1.4
bower jquery-2.1#2.1.4         resolve https://github.com/jquery/jquery-dist.git#2.1.4
bower closure-compiler#*      download https://dl.google.com/closure-compiler/compiler-20140814.zip
bower ng-closure-runner#*     download https://raw.github.com/angular/ng-closure-runner/v0.2.4/assets/ng-closure-runner.zi
p
bower jquery-2.2#2.2.4          cached https://github.com/jquery/jquery-dist.git#2.2.4
bower jquery-2.2#2.2.4        validate 2.2.4 against https://github.com/jquery/jquery-dist.git#2.2.4
bower jquery-2.1#2.1.4        download https://github.com/jquery/jquery-dist/archive/2.1.4.tar.gz
bower jquery#3.1.0            download https://github.com/jquery/jquery-dist/archive/3.1.0.tar.gz
bower closure-compiler#*       extract compiler-20140814.zip
bower closure-compiler#*      resolved https://dl.google.com/closure-compiler/compiler-20140814.zip#e-tag:469db
bower ng-closure-runner#*      extract ng-closure-runner.zip
bower ng-closure-runner#*     resolved https://raw.github.com/angular/ng-closure-runner/v0.2.4/assets/ng-closure-runner.zi
p#e-tag:f9ccc685e
bower jquery-2.1#2.1.4         extract archive.tar.gz
bower jquery#3.1.0             extract archive.tar.gz
bower jquery#3.1.0            resolved https://github.com/jquery/jquery-dist.git#3.1.0
bower jquery-2.1#2.1.4        resolved https://github.com/jquery/jquery-dist.git#2.1.4
bower jquery-2.2#2.2.4         install jquery-2.2#2.2.4
bower closure-compiler#*       install closure-compiler#e-tag:469db
bower ng-closure-runner#*      install ng-closure-runner#e-tag:f9ccc685e
bower jquery#3.1.0             install jquery#3.1.0
bower jquery-2.1#2.1.4         install jquery-2.1#2.1.4

jquery-2.2#2.2.4 bower_components\jquery-2.2

closure-compiler#e-tag:469db bower_components\closure-compiler

ng-closure-runner#e-tag:f9ccc685e bower_components\ng-closure-runner

jquery#3.1.0 bower_components\jquery

jquery-2.1#2.1.4 bower_components\jquery-2.1

mnoon@HORDPC160646 MINGW64 /c/Temp/angtut/angular.js (master)
$ npm install

> iltorb@1.0.13 install C:\Temp\angtut\angular.js\node_modules\iltorb
> node-gyp rebuild

/usr/bin/bash: Files\Git\bin\bash.exe: No such file or directory
angularjs@ C:\Temp\angtut\angular.js
`-- (empty)

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.17: wanted {"os":"darwin","arch":"any"
} (current: {"os":"win32","arch":"x64"})
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "insta
ll"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10
npm ERR! file c:\Program Files\Git\bin\bash.exe
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! iltorb@1.0.13 install: `node-gyp rebuild`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the iltorb@1.0.13 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the iltorb package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs iltorb
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls iltorb
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Temp\angtut\angular.js\npm-debug.log
npm ERR! code 1

mnoon@HORDPC160646 MINGW64 /c/Temp/angtut/angular.js (master)
$ npm --version
3.10.10

mnoon@HORDPC160646 MINGW64 /c/Temp/angtut/angular.js (master)
$ node --version
v6.9.4

mnoon@HORDPC160646 MINGW64 /c/Temp/angtut/angular.js (master)
$ npm bugs iltorb

mnoon@HORDPC160646 MINGW64 /c/Temp/angtut/angular.js (master)
$ npm owner ls litorb
npm ERR! owner ls Couldn't get owner data litorb
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "owner
" "ls" "litorb"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/litorb
npm ERR! 404
npm ERR! 404  'litorb' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Temp\angtut\angular.js\npm-debug.log

mnoon@HORDPC160646 MINGW64 /c/Temp/angtut/angular.js (master)
$

mnoon@HORDPC160646 MINGW64 /c/Temp/angtut/angular.js (master)
$ date
Thu Jan 19 08:05:26 PST 2017

Earlier I was getting different errors:
| | `-- minimatch@3.0.3
| +-- interpret@1.0.1
| `-- rechoir@0.6.2
|   `-- resolve@1.2.0
+-- sorted-object@1.0.0
`-- stringmap@0.2.2

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.17: wanted {"os":"darwin","arch":"any"
} (current: {"os":"win32","arch":"x64"})
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "insta
ll"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10
npm ERR! file c:\Program Files\Git\bin\bash.exe
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! iltorb@1.0.13 install: `node-gyp rebuild`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the iltorb@1.0.13 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the iltorb package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs iltorb
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls iltorb
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Temp\angtut\angular.js\npm-debug.log

mnoon@HORDPC160646 MINGW64 /c/Temp/angtut/angular.js (master)
$

mnoon@HORDPC160646 MINGW64 /c/Temp/angtut/angular.js (master)
$

**Comment by MayhemYDG** [comment]
- `/usr/bin/bash: Files\Git\bin\bash.exe: No such file or directory`
- `npm ERR! file c:\Program Files\Git\bin\bash.exe`

If I read these correclty bash.exe is missing? Or quotes around the path are missing? Maybe try these commands in a normal prompt, outside of mingw64?

**Comment by mncourt** [comment]
Thanks for the info.  I'll try to install that.

**Comment by mncourt** [comment]
You know what... I stupidly reset an environment variable and it had side effects.  After setting it back everything magically works.  I think it was trying to get bash to work on Visual Code editor.
![comspec_environment_variable](https://cloud.githubusercontent.com/assets/25227667/22118462/be63389e-de2c-11e6-94ff-011c726b4de7.png)

**Comment by MayhemYDG** [comment]
:ok_hand: All's good then! Let me know if it still doesn't work.
