### ISSUE TITLE
on amazon ec2, doesn't build

### ISSUE THREAD

**Issue by bingomanatee** [MayhemYDG/iltorb#23]
I am trying to install it in an ec2; what prelims do I need to do to get it running in amazon linux? thanks.

**Comment by MayhemYDG** [comment]
You'll need g++ 4.8 at least.
https://stackoverflow.com/questions/30282091/how-can-i-compile-a-node-c-addon-so-that-i-can-use-distribute-it-on-amazon-aws

**Comment by bingomanatee** [comment]
thanks for the response I have: 

    gcc (GCC) 4.8.3 20140911 (Red Hat 4.8.3-9)

**Comment by MayhemYDG** [comment]
I forgot to mention this guide indicating the dependencies you'll need: https://github.com/nodejs/node-gyp#installation

Let me know if you can't get it to build.

**Comment by bingomanatee** [comment]
my bad -- GCC was actually absent. sorry.

FWIW used 

   yum install gcc-c++

to fix it
