### ISSUE TITLE
No v1.2.0 pre-built binaries for Windows 

### ISSUE THREAD

**Issue by Frank3K** [MayhemYDG/iltorb#29]
When trying to install the latest version using `yarn` (v0.22.0) I get the following error (using Node v6.10.2):

``` sh
node-pre-gyp ERR! Tried to download(404): https://node-iltorb.s3.amazonaws.com/i
ltorb/v1.2.0/node-v48-win32-x64.tar.gz
```

When I look at the listing on https://node-iltorb.s3.amazonaws.com/ (is there a better way to get an overview of the binaries?) I see that v1.2.0 is only built for Darwin and Linux.

BTW, excellent work on the pre-built binaries. Especially on Windows it's a great plus!

**Comment by oohnoitz** [comment]
Taking a look into this. For some reason, AppVeyor didn't publish the binaries to S3.

**Comment by MayhemYDG** [comment]
Bumped to 1.2.1 to update the readme and have the binaries deployed. Should be fixed now.

**Comment by oohnoitz** [comment]
Uploaded the v1.2.0 binaries for Windows in case that is still needed as well.
