### ISSUE TITLE
Brotli 0.6.0

### ISSUE THREAD

**Issue by michel-kraemer** [MayhemYDG/iltorb#32]
Are there any plans to update to Brotli 0.6.0? In the release notes it says the API is now stable and won't change until 1.0.0. So the update might be worthwhile.

**Comment by MayhemYDG** [comment]
Yes, I just need to get around to do this. Unless someone else does it first.

**Comment by MayhemYDG** [comment]
Brotli 0.6.0 is now in iltorb 1.3.0!
