### ISSUE TITLE
Can I use iltorb with Node.js 0.10

### ISSUE THREAD

**Issue by radkodinev** [MayhemYDG/iltorb#4]
Is there any way to use iltorb with Node.js 0.10?
`npm install` fails; I tried using g++4.8 and g++4.9 with `-std=c++11` but no luck.

The reason I need this is adding Brotli support to grunt-contrib-compress (see [PR](https://github.com/gruntjs/grunt-contrib-compress/pull/174)).

**Comment by MayhemYDG** [comment]
I just published 1.0.8 which should add support for Node 0.10.
It compiles and tests fine both on my machine and on Travis, but do let me know if that fixes it for you.

**Comment by radkodinev** [comment]
@MayhemYDG Yes, it builds now! Thanks for the fast reaction and the fix ;)
