### ISSUE TITLE
data over ~1.57MB never seem to finish compressing

### ISSUE THREAD

**Issue by jotto** [MayhemYDG/iltorb#45]
It might have to do with randomness in the file - I can easily compress a large file of zeros, but not JPGs over ~2MB or /dev/random over ~1572864 bytes.

```javascript
// brotli.js
const fs = require("fs");
const compressSync = require("iltorb").compressSync;

const args = process.argv.slice(2);
const filename = args[0];

console.time("compress");
const output = compressSync(fs.readFileSync(filename));
console.timeEnd("compress");
console.log(output.length, "bytes");
```

```bash
// increase to 1572865 to see it fail/stall (or you might need to go a little higher)
dd if=/dev/urandom bs=1 count=1572864 > brotli.txt
node brotli.js brotli.txt
```

**Comment by MayhemYDG** [comment]
Could you confirm this is an issue with iltorb rather than brotli 0.6.0 itself?
https://github.com/google/brotli/releases/tag/v0.6.0

**Comment by jotto** [comment]
Thanks; confirmed.

* 1.2.1 works
* 1.3.0 (google/brotli 0.6.0) is broken.

I think there are existing issues, but I created a new one just in case: https://github.com/google/brotli/issues/584

**Comment by eustas** [comment]
This loop looks suspicious: https://github.com/MayhemYDG/iltorb/blob/master/src/enc/stream_encode_worker.cc#L25
No output space is given; if it happens, that internal brotli output buffer is full - it can't continue processing... so it becomes infinite loop...
Outer wrapper also doesn't care, if chunk is too big to make "StreamEncodeWorker" choke...

**Comment by MayhemYDG** [comment]
@eustas Thank you for looking into this.
Looking back into this, we don't give a buffer to `BrotliEncoderCompressStream` so it can compress as much as possible, then we use `BrotliEncoderTakeOutput`. I was under the impression this is how it would work.
https://github.com/google/brotli/blob/46c1a881b41bb638c76247558aa04b1591af3aa7/include/brotli/encode.h#L315
Should we check `BrotliEncoderHasMoreOutput` on each loop, or is there a way to check to check if brotli's internal buffer is full?

**Comment by eustas** [comment]
Yup, checking `HasMoreOutput` is required.
If input is consumed with unrestricted `TakeOutput`, then no more output **should** arrive without more input (but, currently, there is no contract for that).
It will be better to make it a single loop, with just a little bit more complex exit condition.

**Comment by MayhemYDG** [comment]
@eustas
Cool. Could you do a quick review of this commit?
 1d3f833eb889f2072e32eb3c412d5f583bdee9d0

**Comment by MayhemYDG** [comment]
@jotto should be fine in v1.3.6 now.
