### ISSUE TITLE
install fails on ubuntu xenial

### ISSUE THREAD

**Issue by rabierp** [MayhemYDG/iltorb#47]
Hi,

this fails on my system:
node-pre-gyp install --fallback-to-build

npm -g install firebase-tools
loadDep:@google-cloud/fun ▄ ╢█████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
loadDep:@google-cloud/fun ▀ ╢█████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
/home/pascal/.npm-global/bin/firebase -> /home/pascal/.npm-global/lib/node_modules/firebase-tools/bin/firebase

> iltorb@1.3.4 install /home/pascal/.npm-global/lib/node_modules/firebase-tools/node_modules/iltorb
> node-pre-gyp install --fallback-to-build

/usr/bin/env: «node»: Aucun fichier ou dossier de ce type
/home/pascal/.npm-global/lib
└── (empty)

npm ERR! Linux 4.4.0-83-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "-g" "install" "firebase-tools"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
[npm-debug.log.zip](https://github.com/MayhemYDG/iltorb/files/1240171/npm-debug.log.zip)

npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

**Comment by addaleax** [comment]
That’s really odd. Are you using the node binaries provided by Debian (or maybe Ubuntu?) by any chance? Does `node -v` give you the expected result (v4.2.6)?

**Comment by oohnoitz** [comment]
Looking at the error log attached. This is a permissions issue. Please take a look at https://docs.npmjs.com/getting-started/fixing-npm-permissions.

```
31356 error Error: EACCES: permission denied, access '/usr/local/lib'
31356 error     at Error (native)
31356 error  { [Error: EACCES: permission denied, access '/usr/local/lib']
31356 error   errno: -13,
31356 error   code: 'EACCES',
31356 error   syscall: 'access',
31356 error   path: '/usr/local/lib' }
31357 error Please try running this command again as root/Administrator.
31358 verbose exit [ -13, true ]
```

**Comment by rabierp** [comment]
Hi Anna, Hung,

yes, that was my 1st error.
I already had tried fixing permissions following options 1 & 2 described by
the link you've sent, but that has driven me to the error I had pasted in
the issue (no more an EACCESS ERROR, but a ELIFECYCLE / ENOENT one - that
was after trying option 2 from the link).

Sorry, I should have kept only the last error in the error log.

About your questions Anna:
- system version is Ubuntu 16.04 LTS (Xenial Xerus)
- 'nodejs -v' output is '4.2.6'

Best Regards,
Pascal


Pascal Rabier
https://twitter.com/SWDefinedInfra
France - Europe - World

2017-08-22 0:36 GMT+02:00 Hung Tran <notifications@github.com>:

**Comment by rabierp** [comment]
Hi Anna, Hung,

Issue solved.
I reinstalled entirely nodejs by declaring nodesource.com as a new PPA .
(detailed procedure: https://www.digitalocean.com/community/tutorials/how-to-install-node-js-on-ubuntu-16-04).
No:
- 'node -v' output is '6.11.2'
- everything installs flawlessly (well ... node-pre-gyp falls to to build due to lack of pre-built binary, but that's ok)
Thanks a lot for your help and support,
Best Regards,
Pascal

**Comment by addaleax** [comment]
Yeah, makes sense to me :+1:
