### ISSUE TITLE
Compiling in Windows (AppVeyor)

### ISSUE THREAD

**Issue by radkodinev** [MayhemYDG/iltorb#5]
[google/brotli](https://github.com/google/brotli) seems to compile under Windows as it has an AppVeyor [setup in the repo](https://github.com/google/brotli/search?utf8=%E2%9C%93&q=appveyor).

Can iltorb build under Windows?
I'm trying to integrate it into `grunt-contrib-compress` and currently the [build fails](https://ci.appveyor.com/project/radkodinev/grunt-contrib-compress/build/4).
Any guidelines or help would be highly appreciated. Thanks!

Note: I'm not a Windows user, not a C/C++ developer, and don't have experience with AppVeyor, unfortunately.

**Comment by MayhemYDG** [comment]
I frankly do not know how to build native addons on Windows.

**Comment by MayhemYDG** [comment]
Thanks to @addaleax's work, yes iltorb can indeed be built on Windows. At least on AppVeyor!

**Comment by MayhemYDG** [comment]
@radkodinev Did you get it working? Can we close this issue?

**Comment by radkodinev** [comment]
Hey @MayhemYDG
It works with Node.js 0.12, 4 and 5 which is great. Thanks @addaleax!

I couldn't make it build with Node.js 0.10 though.
I played around with AppVeyor trying to configure it to use a newer Visual Studio version with better support for C++11 features but it looks like it doesn't take effect at all; you can see what I tried [here](https://ci.appveyor.com/project/radkodinev/iltorb/history). Any ideas on this guys?

**Comment by XhmikosR** [comment]
@radkodinev: make sure you call the right script for the MSVC version you want to use; this will set things up properly.

Example for 2015:

```bat
CALL "%VS140COMNTOOLS%..\..\VC\vcvarsall.bat" x86
CALL "%VS140COMNTOOLS%..\..\VC\vcvarsall.bat" amd64
```

You can combine that with the `platform` variable to something like

```bat
if %PLATFORM% == "x86" (
  CALL "%VS140COMNTOOLS%..\..\VC\vcvarsall.bat" x86
) ELSE (
  CALL "%VS140COMNTOOLS%..\..\VC\vcvarsall.bat" amd64
)
```

**Comment by radkodinev** [comment]
Where must that code be put?

**Comment by XhmikosR** [comment]
Since you have the problem in install, there.

**Comment by MayhemYDG** [comment]
@XhmikosR Do you think you could send me a PR with these changes for AppVeyor?

**Comment by XhmikosR** [comment]
I can try it later, sure.

**Comment by radkodinev** [comment]
Thanks @MayhemYDG @XhmikosR !
