### ISSUE TITLE
node-pre-gyp ERR! Tried to download(404): https://github.com/MayhemYDG/iltorb/releases/download/1.3.6/node-v51-win32-x64.tar.gz

### ISSUE THREAD

**Issue by carbitello** [MayhemYDG/iltorb#50]
workdir>npm i iltorb

> iltorb@1.3.6 install workdir\node_modules\iltorb
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://github.com/MayhemYDG/iltorb/releases/download/1.3.6/node-v51-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for iltorb@1.3.6 and node@7.9.0 (node-v51 ABI) (falling back to source compile with node-gyp)

workdir\node_modules\iltorb>if not defined npm_config_node_gyp (node "C:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" clean )  else (node "" c
lean )

workdir\node_modules\iltorb>if not defined npm_config_node_gyp (node "C:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure --fallback-to-
build --module=workdir\node_modules\iltorb\build\bindings\iltorb.node --module_name=iltorb --module_path=workdir\node_modules\iltorb\build\bindings )  else (node "" configure
--fallback-to-build --module=workdir\node_modules\iltorb\build\bindings\iltorb.node --module_name=iltorb --module_path=workdir\node_modules\iltorb\build\bindings )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:454:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:480:16)
gyp ERR! stack     at C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:114:15)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=workdir\\node_modules\\iltorb\\build\\bindings\\iltorb.node" "--module_name=iltorb" "--module_path=workdir\\node_modules\\iltorb\\build\\bindings"
gyp ERR! cwd workdir\node_modules\iltorb
gyp ERR! node -v v7.9.0
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=workdir\node_modules\iltorb\build\bindings\iltorb.node --module_name=iltorb --module_path=C:\Logify\Si
mpleViewerTests\TestCafe\node_modules\iltorb\build\bindings' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (workdir\node_modules\iltorb\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:899:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Windows_NT 6.3.9600
node-pre-gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "workdir\\node_modules\\iltorb\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd workdir\node_modules\iltorb
node-pre-gyp ERR! node -v v7.9.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.35
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=workdir\node_modules\iltorb\build\bindings\iltorb.node --module_name=iltorb --module_path=workdir\node_m
odules\iltorb\build\bindings' (1)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN babel-eslint@5.0.4 requires a peer of eslint@<2.3.0 but none was installed.
npm WARN application-name@0.0.1 No description
npm WARN application-name@0.0.1 No repository field.
npm WARN application-name@0.0.1 No license field.
npm WARN Error: EPERM: operation not permitted, scandir 'workdir\node_modules\iltorb\node_modules\verror\node_modules'
npm WARN  { Error: EPERM: operation not permitted, scandir 'workdir\node_modules\iltorb\node_modules\verror\node_modules'
npm WARN   errno: -4048,
npm WARN   code: 'EPERM',
npm WARN   syscall: 'scandir',
npm WARN   path: 'workdir\\node_modules\\iltorb\\node_modules\\verror\\node_modules' }
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "iltorb"
npm ERR! node v7.9.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1

npm ERR! iltorb@1.3.6 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the iltorb@1.3.6 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the iltorb package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs iltorb
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls iltorb
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\User\AppData\Roaming\npm-cache\_logs\2017-09-26T14_02_07_836Z-debug.log

workdir>

**Comment by oohnoitz** [comment]
We don't provide binaries for `Node.js v7.x` and it doesn't seem like you have the build requirements fulfilled (which can be found in the README).

**Comment by oohnoitz** [comment]
Closing this out since the error is related to build tools not being available locally. The solution would be to either:
- install the required build tools (check the README)
- or use any version we provide a compiled binary (see AppVeyor or Travis-CI for supported versions)
