### ISSUE TITLE
node-pre-gyp prebuilt binary seg faults on Alpine Linux

### ISSUE THREAD

**Issue by TooTallNate** [MayhemYDG/iltorb#51]
From running gdb, I see a seg fault coming from `BuildAndStoreBlockSplitCode`.

This Dockerfile is a minimal repro case:

```
FROM mhart/alpine-node:8
RUN apk add --no-cache make gcc g++ python
RUN npm install iltorb
CMD node -p "require('iltorb').compressSync(new Buffer('hello'));"
```

To run:

```
$ docker build -t iltorb-seg-fault .
$ docker run --rm iltorb-seg-fault
Segmentation fault
```

The node-pre-gyp prebuilt Linux binary is at fault, because if I add `--build-from-source`, it works correctly:

```
FROM mhart/alpine-node:8
RUN apk add --no-cache make gcc g++ python
RUN npm install iltorb --build-from-source
CMD node -p "require('iltorb').compressSync(new Buffer('hello'));"
```

```
$ docker build -t iltorb-build-from-source .
$ docker run --rm iltorb-build-from-source
<Buffer 0b 02 80 68 65 6c 6c 6f 03>
```

**Comment by oohnoitz** [comment]
I'll need to look into a better way to support both glibc and musl. All of our binaries are only configured to build against glibc due to our current build/install pipeline for binaries. Won't be able to get to this until later this week though.

**Comment by oohnoitz** [comment]
@TooTallNate This should be resolved in `v1.3.9`.

**Comment by core-process** [comment]
@oohnoitz `node-pre-gyp` just released a new version, which support the `{libc}` token in the path and package name variables. The token resolves to `glibc` or `musl`.

See:
- https://github.com/mapbox/node-pre-gyp/blob/master/CHANGELOG.md#0639
- https://github.com/mapbox/node-pre-gyp/blob/master/README.md#versioning
- Working example: https://github.com/core-process/snapsync/blob/master/node/package.json#L14-L15

**Comment by oohnoitz** [comment]
@core-process we already resolved this issue by switching over to `prebuild` instead which already supports that same functionality.
