### ISSUE TITLE
Add prebuilt binaries for more recent Node versions?

### ISSUE THREAD

**Issue by fagerbua** [MayhemYDG/iltorb#56]
From the list at https://github.com/MayhemYDG/iltorb/releases it seems that the most recent Node version that has a precompiled binary is 5.9. Would it be possible to add binaries for some more recent versions? If yes – is there anything I can do to help?

**Comment by MayhemYDG** [comment]
`v59` references Node's module version, not Node version 5.9. We support Node 4, 6, 8 and 9.
https://github.com/nodejs/node/blob/master/src/node_version.h#L106
Are you having any issues with pre-compiled binaries?

**Comment by fagerbua** [comment]
Thanks for clarifying! On further inspection I see that our problem is caused by github not being accessible from our CI environment. What we'd need in order to use the precompiled binaries is an option to specify the download path, but I'm not sure if that is possible without maintaining our own fork.

**Comment by oohnoitz** [comment]
@fagerbua we use the `prebuild` package to handle generating and installing the binaries. what you might be looking for is https://github.com/prebuild/prebuild-install/pull/46, but that hasn't been merged in upstream yet.

**Comment by MayhemYDG** [comment]
When it fails to fetch the binaries, does it attempt to build the binaries or does it fall on its face?
If it's trying to build, you should setup your CI so it's capable of building the binaries.
https://github.com/MayhemYDG/iltorb#prerequisites-for-building

**Comment by fagerbua** [comment]
@oohnoitz Thanks, that's exactly what we need!

@MayhemYDG The build works alright. It's just a little bit annoying to have to build it every time.

**Comment by MayhemYDG** [comment]
Cache your `node_modules`! If you can.
Copy the node_modules folder after each `npm install`, and pate the copy before `npm install`, then you won't need to build or download every deps on each CI run.

**Comment by fagerbua** [comment]
Clever, hadn't thought of that. Might be worth the effort!
