### ISSUE TITLE
Upgrade `prebuild-install` to avoid `npm audit` security vulnerability

### ISSUE THREAD

**Issue by ehmicky** [MayhemYDG/iltorb#69]
This package is marked as vulnerable by `npm audit` because of a deep dependency on this [deep-extend vulnerability](https://nodesecurity.io/advisories/612). 

It can be fixed by upgrading `prebuild-install` from `3.0.0` to `4.0.0`.

**Comment by MayhemYDG** [comment]
```
$ npm audit

                       === npm audit security report ===


                                 Manual Review
             Some vulnerabilities require your attention to resolve

          Visit https://go.npm.me/audit-guide for additional guidance


  Low             Prototype Pollution

  Package         lodash

  Patched in      >=4.17.5

  Dependency of   prebuild [dev]

  Path            prebuild > cmake-js > lodash

  More info       https://nodesecurity.io/advisories/577


[!] 1 vulnerability found - Packages audited: 1378 (1232 dev, 30 optional)
    Severity: 1 Low
```
`build-install` doesn't exist, and I'm getting a different security warning. Are you auditing a different package perhaps?

**Comment by MayhemYDG** [comment]
Regarding `prebuild-install`, its dependency on `rc` is set as `"rc": "^1.1.6",`, and the latest version is `1.2.7`, so installing iltorb should install the latest version of rc with the fixed `deep-extend`.

Perhaps you need to update your `package-lock.json` file?
I'm not getting any security warning on my side when installing iltorb as a dependency.

**Comment by ehmicky** [comment]
Yes this was because I did not update my `package-lock.json`. Really sorry about the false alarm!
