### ISSUE TITLE
Can you bundle iltorb.node file with in node module instead of downloading from github

### ISSUE THREAD

**Issue by tnpradeep** [MayhemYDG/iltorb#72]
Hi 

install script tries to download iltorb.node from github which is blocked by corporate firewall. Because of this I am not able to build swagger UI.

Is it possible to bundle this file as part of node module which is available at https://registry.npmjs.org/iltorb/-/iltorb-1.3.10.tgz.

Thanks
Pradeep

**Comment by MayhemYDG** [comment]
@tnpradeep 
If you can't download the pre-built binaries, it will try to build them locally.
https://github.com/MayhemYDG/iltorb#prerequisites-for-building
https://github.com/nodejs/node-gyp#installation
Is it possible for you to install the necessary build tools?

**Comment by tnpradeep** [comment]
Can I mirror this tar.gz file in out local repository and point it to this path using some environment variable ? Like the way node-saas has implemented.
Reference : https://github.com/sass/node-sass#binary-configuration-parameters

**Comment by oohnoitz** [comment]
Yes, there is a similar mirror option already available and can be done with the following methods https://github.com/prebuild/prebuild-install#custom-binaries.

1) `.npmrc`
    ```
    iltorb_binary_host=https://domain.tld/path
    ```

2) `ENV` variable
    ```
    npm_config_iltorb_binary_host=https://domain.tld/path npm i iltorb
    ```

Both of these would result in attempting to download the binary from the following location:
```
https://download.tld/path/v2.3.2/iltorb-v2.3.2-node-v57-linux-64.tar.gz
```

**Comment by oohnoitz** [comment]
Closing this as its now documented in the [README](https://github.com/MayhemYDG/iltorb#troubleshooting).
