### ISSUE TITLE
Module doesn't work on Trusty Ubuntu 14.04

### ISSUE THREAD

**Issue by reduxdj** [MayhemYDG/iltorb#74]

**Comment by oohnoitz** [comment]
@reduxdj could you provide some details/stacktrace/etc?

**Comment by MayhemYDG** [comment]
Make sure your node version is up to date so it supports n-api: latest node 6, 8 or 10.

**Comment by reduxdj** [comment]
on osx same issue

info looking for cached prebuild @ /Users/patricklemiuex/.npm/_prebuilds/9415e2-iltorb-v2.4.0-node-v57-darwin-x64.tar.gz
info found cached prebuild
info unpacking @ /Users/patricklemiuex/.npm/_prebuilds/9415e2-iltorb-v2.4.0-node-v57-darwin-x64.tar.gz
info unpack resolved to /Users/patricklemiuex/projects/iflipd-admin-reactql/node_modules/iltorb/build/bindings/iltorb.node
WARN install The module '/Users/patricklemiuex/projects/iflipd-admin-reactql/node_modules/iltorb/build/bindings/iltorb.node'
WARN install was compiled against the ABI-stable Node.js API (N-API).
WARN install This feature is experimental and must be enabled on the
WARN install command-line by adding --napi-modules.
  CC(target) Release/obj.target/iltorb/brotli/c/common/dictionary.o
  CC(target) Release/obj.target/iltorb/brotli/c/common/transform.o
  CC(target) Release/obj.target/iltorb/brotli/c/dec/bit_reader.o
  CC(target) Release/obj.target/iltorb/brotli/c/dec/decode.o
  CC(target) Release/obj.target/iltorb/brotli/c/dec/huffman.o
  CC(target) Release/obj.target/iltorb/brotli/c/dec/state.o
  CC(target) Release/obj.target/iltorb/brotli/c/enc/backward_references.o
  CC(target) Release/obj.target/iltorb/brotli/c/enc/backward_references_hq.o
  CC(target) Release/obj.target/iltorb/brotli/c/enc/bit_cost.o
  CC(target) Release/obj.target/iltorb/brotli/c/enc/block_splitter.o
  CC(target) Release/obj.target/iltorb/brotli/c/enc/brotli_bit_stream.o
  CC(target) Release/obj.target/iltorb/brotli/c/enc/cluster.o
  CC(target) Release/obj.target/iltorb/brotli/c/enc/compress_fragment.o
  CC(target) Release/obj.target/iltorb/brotli/c/enc/compress_fragment_two_pass.o
  CC(target) Release/obj.target/iltorb/brotli/c/enc/dictionary_hash.o
  CC(target) Release/obj.target/iltorb/brotli/c/enc/encode.o
  CC(target) Release/obj.target/iltorb/brotli/c/enc/encoder_dict.o
  CC(target) Release/obj.target/iltorb/brotli/c/enc/entropy_encode.o
  CC(target) Release/obj.target/iltorb/brotli/c/enc/histogram.o
  CC(target) Release/obj.target/iltorb/brotli/c/enc/literal_cost.o
  CC(target) Release/obj.target/iltorb/brotli/c/enc/memory.o
  CC(target) Release/obj.target/iltorb/brotli/c/enc/metablock.o
  CC(target) Release/obj.target/iltorb/brotli/c/enc/static_dict.o
  CC(target) Release/obj.target/iltorb/brotli/c/enc/utf8_util.o
  CXX(target) Release/obj.target/iltorb/src/common/allocator.o
  CXX(target) Release/obj.target/iltorb/src/common/stream_coder.o
  CXX(target) Release/obj.target/iltorb/src/dec/stream_decode.o
../src/dec/stream_decode.cc:26:42: error: use of undeclared identifier 'NAPI_AUTO_LENGTH'
  napi_define_class(env, "StreamDecode", NAPI_AUTO_LENGTH, New, nullptr, 2, properties, &cons);
                                         ^
1 error generated.
make: *** [Release/obj.target/iltorb/src/dec/stream_decode.o] Error 1

**Comment by MayhemYDG** [comment]
@reduxdj what version of Node are you running?

**Comment by reduxdj** [comment]
WARN install command-line by adding --napi-modules.
  CC(target) Release/obj.target/iltorb/brotli/c/common/dictionary.o
  CC(target) Release/obj.target/iltorb/brotli/c/common/transform.o
  CC(target) Release/obj.target/iltorb/brotli/c/dec/bit_reader.o
  CC(target) Release/obj.target/iltorb/brotli/c/dec/decode.o
  CC(target) Release/obj.target/iltorb/brotli/c/dec/huffman.o
  CC(target) Release/obj.target/iltorb/brotli/c/dec/state.o
  CC(target) Release/obj.target/iltorb/brotli/c/enc/backward_references.o
  CC(target) Release/obj.target/iltorb/brotli/c/enc/backward_references_hq.o
  CC(target) Release/obj.target/iltorb/brotli/c/enc/bit_cost.o
  CC(target) Release/obj.target/iltorb/brotli/c/enc/block_splitter.o
  CC(target) Release/obj.target/iltorb/brotli/c/enc/brotli_bit_stream.o
  CC(target) Release/obj.target/iltorb/brotli/c/enc/cluster.o
  CC(target) Release/obj.target/iltorb/brotli/c/enc/compress_fragment.o
  CC(target) Release/obj.target/iltorb/brotli/c/enc/compress_fragment_two_pass.o
  CC(target) Release/obj.target/iltorb/brotli/c/enc/dictionary_hash.o
  CC(target) Release/obj.target/iltorb/brotli/c/enc/encode.o
  CC(target) Release/obj.target/iltorb/brotli/c/enc/encoder_dict.o
  CC(target) Release/obj.target/iltorb/brotli/c/enc/entropy_encode.o
  CC(target) Release/obj.target/iltorb/brotli/c/enc/histogram.o
  CC(target) Release/obj.target/iltorb/brotli/c/enc/literal_cost.o
  CC(target) Release/obj.target/iltorb/brotli/c/enc/memory.o
  CC(target) Release/obj.target/iltorb/brotli/c/enc/metablock.o
  CC(target) Release/obj.target/iltorb/brotli/c/enc/static_dict.o
  CC(target) Release/obj.target/iltorb/brotli/c/enc/utf8_util.o
  CXX(target) Release/obj.target/iltorb/src/common/allocator.o
  CXX(target) Release/obj.target/iltorb/src/common/stream_coder.o
  CXX(target) Release/obj.target/iltorb/src/dec/stream_decode.o
../src/dec/stream_decode.cc:26:42: error: use of undeclared identifier 'NAPI_AUTO_LENGTH'
  napi_define_class(env, "StreamDecode", NAPI_AUTO_LENGTH, New, nullptr, 2, properties, &cons);
                                         ^
1 error generated.
make: *** [Release/obj.target/iltorb/src/dec/stream_decode.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 17.5.0
gyp ERR! command "/usr/local/Cellar/node/10.5.0_1/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/patricklemiuex/projects/iflipd-admin-reactql/node_modules/iltorb
gyp ERR! node -v v8.5.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

**Comment by MayhemYDG** [comment]
@reduxdj Node v8.5.0 is outdated, please update to the latest version: Node v8.11.3.
