### ISSUE TITLE
Add Windows build for node 11?

### ISSUE THREAD

**Issue by ForsakenHarmony** [MayhemYDG/iltorb#79]

**Comment by MayhemYDG** [comment]
https://github.com/appveyor/ci/issues/2707
We're waiting on AppVeyor to add support for Node 11. Right now AppVeyor builds with Node 11 are failing.

**Comment by molant** [comment]
@MayhemYDG will it be possible to start a new build? Looks like [`node-sass` is already using it](https://github.com/appveyor/ci/issues/2707#issuecomment-437180923)

**Comment by oohnoitz** [comment]
Uploaded the build artifacts for Node 11 x64/x84. Going to close this out.
