### ISSUE TITLE
Make the compression stream flushable

### ISSUE THREAD

**Issue by bryanburgers** [MayhemYDG/iltorb#8]
zlib compression streams (gzip, deflat) have a way to [flush](https://nodejs.org/api/zlib.html#zlib_zlib_flush_kind_callback) the stream, which allows a TCP stream that sends irregularly sized messages to call `flush` and send the data that's been written down the pipe, even if the compression is in a state where it would otherwise wait for more data to create an ideal block.

I don't know much about brotli (or gzip/deflate, so maybe my explanation above is lacking), so I'm not even sure if this is a use case that brotli supports from a technical standpoint or if it is something that the underlying brotli library exposes to the iltorb module. I'd love to hear either way.

But if it is possible, adding a flush method that mirrors the zlib API for this would be helpful.

**Comment by MayhemYDG** [comment]
It does look like this could be possible:
https://github.com/google/brotli/blob/b820c39/enc/encode.h#L118

The Node API docs say: "Don't call this frivolously, premature flushes negatively impact the effectiveness of the compression algorithm."
This applies to brotli as well.

**Comment by oohnoitz** [comment]
Available in v1.2.0.

**Comment by MayhemYDG** [comment]
@bryanburgers please let us know if you encounter any issue when making use of flushing.
