### ISSUE TITLE
Occasional Segmentation faults when running in Docker

### ISSUE THREAD

**Issue by tpbowden** [MayhemYDG/iltorb#82]
I'm fairly sure that running Iltorb (2.4.1) in Docker (`node-10.15`) is causing occasional segmentation faults. I can't get it to print out enough information to prove it, but when I remove Iltorb the errors stop occurring.

We are calling `iltorb.compress(input, {}, callback)`

Do you have any advice on how I can further debug this or provide some more helpful information? I can't consistently reproduce it.

**Comment by MayhemYDG** [comment]
Could you try using version 2.3.2 of iltorb instead? We've replaced NAN with N-API in version 2.4.0, it's possible the issue lies in N-API or our usage of it.

**Comment by tpbowden** [comment]
Thanks for the reply, I'll try that and let you know how it goes. Another observation I made is that it only seems to happen once. After a segfault, all subsequent runs of Iltorb work perfectly (still using 2.4.1)

**Comment by tpbowden** [comment]
Downgrading seems to have fixed it but I will let it run like this for a while and update if it occurs again

**Comment by magnus-bergman** [comment]
I've experienced this a lot recently as well, and can confirm 2.3.2 works much better.

**Comment by oohnoitz** [comment]
@MayhemYDG maybe we should temporarily switch back to `nan` and create a new release so people don't run into this issue randomly. We can move `n-api` changes to an experimental branch to see if we can figure out why these _random_ segfaults are happening.

**Comment by MayhemYDG** [comment]
I've published 2.4.2, which reverts things back to NAN, let me know if it all works well.

**Comment by tpbowden** [comment]
`2.4.2` works fine, thanks!
