### ISSUE TITLE
node-gyp < 4.0.0 has a vulnerability in the tar package dependency

### ISSUE THREAD

**Issue by giamir** [MayhemYDG/iltorb#87]
You should consider upgrading to node-gyp version 4.0.0 which uses version 4.4.8 of the tar package and therefore it is patched.
https://github.com/nodejs/node-gyp/commit/1456ef27c72cc4e49f9b1d82cbb047cb673156c8

**Comment by MayhemYDG** [comment]
Thanks for letting us know, we'll look into it asap.

**Comment by oohnoitz** [comment]
@MayhemYDG let's roll out https://dependabot.com/ on this repo. I don't have access but this will let us manage dependencies a bit better and automate some of the stuff for us.

**Comment by MayhemYDG** [comment]
@giamir this is now fixed and published in version 2.4.3.

@oohnoitz we could look into it yeah.
GitHub has a similar feature, I wonder why it didn't notify me though:
![image](https://user-images.githubusercontent.com/567105/56695415-ec9e1000-66e0-11e9-96fc-64184d1a3ae4.png)

**Comment by oohnoitz** [comment]
Well, opting for dependabot mostly cause it can create PRs for us and we'd just need to keep an eye on those instead.

**Comment by giamir** [comment]
Thanks a lot for the prompt fix. 👍
