### ISSUE TITLE
v8 deprecation: v8::ObjectTemplate::Set()

### ISSUE THREAD

**Issue by silverwind** [MayhemYDG/iltorb#9]
Requiring this module under Node.js v6.0.0 currently results in multiple deprecation messages like
````
(node) v8::ObjectTemplate::Set() with non-primitive values is deprecated
(node) and will stop working in the next major release.
````

I think these are the offending lines:

https://github.com/MayhemYDG/iltorb/blob/61c83ad69639b9de6ba72d31e3fdba8fd8086cfb/src/enc/encode_index.cc#L25
https://github.com/MayhemYDG/iltorb/blob/61c83ad69639b9de6ba72d31e3fdba8fd8086cfb/src/dec/decode_index.cc#L26

**Comment by MayhemYDG** [comment]
I'm sorry but I can't reproduce this issue, are you sure it's coming from iltorb?

**Comment by silverwind** [comment]
Certainly, the stack trace below point to its files. I'm seeing

- 3 messages for `node_modules\iltorb\build\Release\encode.node`:
````
    1: .node [module.js:568] [pc=0000028818497DC4] (this=000002B8A6B07329 <an Ob
ject with map 0000035779117241>#1#,module=000002FDDF0CB6D9 <a Module with map 00
00035779117819>#2#,filename=000002FDDF0CB6B1 <String[59]: C:\git\droppy\node_mod
ules\iltorb\build\Release\encode.node>)
````

- 2 messages for `node_modules\iltorb\build\Release\decode.node`
````
    1: .node [module.js:568] [pc=0000028818497DC4] (this=000002B8A6B07329 <an Ob
ject with map 0000035779117241>#1#,module=000002FDDF0CF659 <a Module with map 00
00035779117819>#2#,filename=000002FDDF0CF631 <String[59]: C:\git\droppy\node_mod
ules\iltorb\build\Release\decode.node>)
````
Note that I edited my fist message, it doesn't show at build time, but at runtime. It's on Windows, but I doubt it matters.

**Comment by MayhemYDG** [comment]
Did you run `npm rebuild`?

**Comment by addaleax** [comment]
Sorry if this is pointless, but I think this is fixed by (re)compiling with a recent nan version.

**Comment by silverwind** [comment]
Guess I just fixed it. I indeed did a `npm rebuild` before, but apparently the issue has gone away now with a `rm node_modules && npm i`. Sorry for the trouble!
